"""add created_at and updated_at fields

Revision ID: ad627b184aa2
Revises: 2988054f6c57
Create Date: 2025-11-08 12:10:37.019591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad627b184aa2'
down_revision: Union[str, None] = '2988054f6c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('services', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'updated_at')
    op.drop_column('services', 'created_at')
    # ### end Alembic commands ###
